version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
            - redis

    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
            #- .:/var/lib/postgresql/
        ports:
            - 5432:5432

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        command: redis-server --requirepass pass
        environment:
            - REDIS_HOST=localhost
            - REDIS_PORT=6379
            - REDIS_PASSWORD=pass

    
volumes:
    pgdata: