# Generated by Django 4.1.1 on 2022-11-13 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_alter_subject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
