# Generated by Django 4.1.1 on 2022-11-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_alter_subject_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendance',
            name='stsu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.studentsubject'),
        ),
    ]
