# Generated by Django 4.1.1 on 2022-11-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_alter_subject_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], max_length=8),
        ),
    ]
