# Generated by Django 4.1.1 on 2022-11-17 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0012_alter_attendance_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 10, 30, 58, 16211)),
        ),
    ]
