# Generated by Django 4.1.1 on 2022-11-17 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0013_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 10, 35, 16, 493228, tzinfo=datetime.timezone.utc)),
        ),
    ]
