# Generated by Django 4.1.1 on 2022-11-25 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0014_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 5, 39, 39, 13001, tzinfo=datetime.timezone.utc)),
        ),
    ]
