# Generated by Django 4.1.1 on 2022-12-11 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0015_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 9, 46, 36, 362220, tzinfo=datetime.timezone.utc)),
        ),
    ]
