# Generated by Django 4.1.1 on 2022-12-04 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0016_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 13, 11, 26, 166831, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='point',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
