# Generated by Django 4.1.1 on 2022-12-10 05:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0017_alter_attendance_date_alter_point_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 5, 7, 15, 597778, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
