# Generated by Django 4.1.1 on 2022-12-11 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0017_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 14, 4, 16, 882750, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Unverified', 'unverified'), ('Verified', 'verified'), ('Deactivated', 'deactivated')], default='Unverified', max_length=25),
        ),
    ]
